# https://gitea.treehouse.systems/ariadne/ariadne.space/src/branch/main/.woodpecker.yml
pipeline:
  telegram-bot-api:
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      repo: gitea.nulo.in/Nulo/dlbot4/telegram-bot-api
      context: ./telegram-bot-api-container
      registry: https://gitea.nulo.in
      username: Nulo
      password:
        from_secret: registry_secret
    secrets: [REGISTRY_SECRET]
    when:
      branch: "antifascista"
      event: "push"
