package:
  name: dlbot
  version: 4.0.0
  epoch: 0
  description: "downloader bot for Telegram"
  target-architecture:
    - all
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.17/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.17/community
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - name: Build application
    runs: |
      go build -o "${{targets.destdir}}/usr/bin/dlbot"
