version: "3"

tasks:
  build:
    cmds:
      - go build -tags=netgo .
  ko:
    cmds:
      - docker run --rm -it
        -v ~/.docker/:/docker-config,ro
        -v $PWD:/work
        --workdir=/work
        -e KO_DOCKER_REPO=gitea.nulo.in/nulo/dlbot4
        -e DOCKER_CONFIG=/docker-config
        cgr.dev/chainguard/ko build --bare .
