version: "3"

tasks:
  build:
    cmds:
      - go build -tags=netgo .
  upload:
    deps:
      - task: build
    cmds:
      - ssh -p993 root@nulo.in sv stop dlbot
      - scp -P993 dlbot dlbot@nulo.in:/home/dlbot/bin/
      - ssh -p993 root@nulo.in sv start dlbot
  ko:
    cmds:
      - podman run --rm -it
        -v ~/.docker/:/docker-config:Z,ro
        -v $PWD:/work:Z
        --workdir=/work
        -e KO_DOCKER_REPO=gitea.nulo.in/nulo/dlbot4
        -e DOCKER_CONFIG=/docker-config
        cgr.dev/chainguard/ko build --bare .
