FROM docker.io/alpine:3.18 AS build

RUN apk add --no-cache \
    make cmake \
    g++ \
    gperf \
    linux-headers openssl-dev \
    zlib-dev \
    git

RUN git clone --recursive https://github.com/tdlib/telegram-bot-api.git && \
    cd telegram-bot-api/ && \
    mkdir build && \
    cd build

WORKDIR telegram-bot-api/build

RUN cmake .. -DCMAKE_BUILD_TYPE=Release \
    && cmake --build . --target install

FROM docker.io/alpine:3.18
ENV TZ=America/Argentina/Buenos_Aires

RUN apk add --no-cache \
    openssl \
    zlib \
    libstdc++

COPY --from=build /usr/local/bin/telegram-bot-api /usr/local/bin/telegram-bot-api

ENTRYPOINT telegram-bot-api

EXPOSE 8081
